= misc_py_tools

Miscellanous tools written in Python for a series of tasks

== Background

On June 9th, 2016, I deleted many useful tools that I had been using for some
time. This repo is dedicated to those scripts which were so helpful to me. I
am in the process of recreating them. They will be available on GitHub so that
I will never lose them again, and so that anyone can take advantage of them.

== Contents

Currently, the only somewhat completed script is the CD Ripper which can be
found at 'Audio/ripper.py'. Sooner or later this will receive its own repo,
but for now it will remain miscellaneous.

=== Audio

This folder contains an assortment of audio file related scripts, including a 
CD ripper which uses CDParanoia and FFmpeg to create audio files specified in
a build script. It is working quite well as of 06/27/2016.

This folder also has a small mutagen wrapper for printing metadata from files,
but it is not really complete yet.

=== General

Literally just a bunch of general test scripts and other junk.

== License

These scripts are all available under the MIT Open Source license. Read
'LICENSE' for more information.
